### ISSUE TITLE
[선택 정렬] 선택 정렬의 장점

### ISSUE THREAD

**Issue by YuGyeong98** [YuGyeong98/CS-Drill#1]
선택 정렬의 장점 중에서 '내림차순으로 정렬되어있는 요소를 오름차순으로 재정렬할 때 효율이 좋다' 라는 얘기가 있는데, 어떤 점에서 효율이 좋은가요?
매번 최솟값을 정하고, 비교하는 건 똑같지 않나요?

**Comment by nuyhus-m** [comment]
https://kimmeh1.tistory.com/529
정렬을 할 때 빈번한 교환은 비효율적인데
선택 정렬은 역순 정렬에서 한 번의 교환으로 두 개의 수를 알맞은 위치로 저장할 수 있기 때문에
항상 최대 원소의 개수의 반(N/2)만큼만 교환이 일어나게 됩니다.
따라서 역순 정렬을 할 때는 선택 정렬을 사용하는 것이 효율적입니다!
