### ISSUE TITLE
[객체 지향 프로그래밍] 캡슐화 - 코틀린 접근 제어자

### ISSUE THREAD

**Issue by YuGyeong98** [YuGyeong98/CS-Drill#4]
https://kotlinlang.org/docs/visibility-modifiers.html#class-members

코틀린 접근 제어자 중에서 protected가 같은 모듈 안에서 참조 가능하다고 되어있는데,
private이랑 동일하니까 '선언한 클래스 내부 + 서브 클래스에서 참조 가능' 이렇게 변경하면 좋을 것 같습니다!

**Comment by juhan2103** [comment]
> https://kotlinlang.org/docs/visibility-modifiers.html#class-members
> 
> 코틀린 접근 제어자 중에서 protected가 같은 모듈 안에서 참조 가능하다고 되어있는데, private이랑 동일하니까 '선언한 클래스 내부 + 서브 클래스에서 참조 가능' 이렇게 변경하면 좋을 것 같습니다!

조언 감사합니다! 수정하겠습니다!

**Comment by juhan2103** [comment]
@YuGyeong98 반영 완료 했습니다!
