### ISSUE TITLE
[데이터베이스 기초] 데이터 정의 언어(DDL)

### ISSUE THREAD

**Issue by juhan2103** [YuGyeong98/CS-Drill#5]
DDL의 명령어로 CREATE, ALTER, DELETE를 적어 주셨는데 DELETE는 DDL이 아닌 DML(데이터 조작 언어) 인것 같습니다!
DELETE 말고 DROP을 사용하는 것이 맞는것 같습니다. 그리고 TRUNCATE도 같은 DDL이므로 추가하는게 좋을 것 같습니다!

[데이터 정의 언어](https://ko.wikipedia.org/wiki/%EB%8D%B0%EC%9D%B4%ED%84%B0_%EC%A0%95%EC%9D%98_%EC%96%B8%EC%96%B4)

**DDL 명령어**
| 명령어 | 설명 |
| --- | --- |
| CREATE | 새로운 데이터베이스 관계 생성 |
| DROP | 이미 존재하는 데이터베이스 관계를 제거 |
| ALTER |  이미 존재하는 데이터베이스 개체에 대한 변경 역할 |
| TRUNCATE |  테이블을 초기화 시키는 역할 |

**Comment by YuGyeong98** [comment]
감사합니다 수정 완료했습니다!
TRUNCATE도 추가 완료했습니다!😀
