### ISSUE TITLE
[합병 정렬] 합병 정렬 예제 코드

### ISSUE THREAD

**Issue by juhan2103** [YuGyeong98/CS-Drill#6]
혹시 배열 크기가 홀수일 때도 계산되어 있는 코드인가요? 배열 크기를 홀수로 했을 때는 제대로 정렬되지 않아 질문드립니다!

**Comment by nuyhus-m** [comment]
정렬할 배열의 크기랑
정렬된 숫자들을 저장할 임시 배열의 크기를 똑같이 바꾸고
코드를 실행해야 합니당
