### ISSUE TITLE
[고정 소수점 & 부동 소수점] 정수부와 소수부

### ISSUE THREAD

**Issue by YuGyeong98** [YuGyeong98/CS-Drill#8]
부동 소수점 방식 부분에서 '고정 소수점은 정수부와 실수부를 나누어서 나타낸다'라는 얘기가 있는데, 소수부를 실수부라고도 하는지 궁금합니다!

---
간단한 오타 있어서 일단 적어두겠습니다!
1. 그 다음으로 넘어갔을 때 2의 1제곱 자리이므로 2 * 1 = 1이 된다. -> 여기서 1이 2로 변경되어야 될 것 같습니다.
2. 부동 소수점(Floating Point) 방식
3. 부동 소수점 방식의 오차
```kotlin
val result = 0
for (i 0 until 1000) {
    result += 0.1
}
``` 
아래 코드로 변경되어야 될 것 같습니다.
```kotlin
var result = 0.0
for (i in 0 until 1000) {
    result += 0.1
}
```

**Comment by juhan2103** [comment]
> 부동 소수점 방식 부분에서 '고정 소수점은 정수부와 실수부를 나누어서 나타낸다'라는 얘기가 있는데, 소수부를 실수부라고도 하는지 궁금합니다!
> 
> 간단한 오타 있어서 일단 적어두겠습니다!
> 
> 1. 그 다음으로 넘어갔을 때 2의 1제곱 자리이므로 2 * 1 = 1이 된다. -> 여기서 1이 2로 변경되어야 될 것 같습니다.
> 2. 부동 소수점(Floating Point) 방식
> 3. 부동 소수점 방식의 오차
> 
> ```kotlin
> val result = 0
> for (i 0 until 1000) {
>     result += 0.1
> }
> ```
> 
> 아래 코드로 변경되어야 될 것 같습니다.
> 
> ```kotlin
> var result = 0.0
> for (i in 0 until 1000) {
>     result += 0.1
> }
> ```

수정 완료했습니다!

**Comment by juhan2103** [comment]
@YuGyeong98 수정 완료했습니다!
